name: Build Java & Build Docker Image

on: [push]

jobs:
  build-docker-image:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Build Docker image
        run: docker build . --tag ranadekanak/feedback-api:$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        
      - name: Push Docker image
        run: docker push ranadekanak/feedback-api:$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
 
